#server config
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#mybatis config
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*Mapper.xml



#spring config
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:mariadb://106.245.226.42:33306/pixelviewer?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&autoReconnect=true
#    username: root
#    password: pass0001
    username: pixelviewer
    password: Pass0001!
    hikari:
      maximum-pool-size: 10
#      connection-timeout: 300000
#      idle-timeout: 8000
#      leakDetectionThreshold: 300000
#      minimum-idle: 10
#      testWhileIdle: true
#      max-lifetime: 1200000

values:
  protocol: "http://"
  was:
    ip: "106.245.226.42"
    port: "4006"
    path: "/api-viewer/"
  agent:
    ip: "192.168.123.12"
    port: "8800"
    path: "/vieweragent/Preset/layer-placement"
